from __future__ import annotations

from enum import StrEnum


class ErrorCode(StrEnum):
    FRAME_DECODE_FAILED = "FRAME_DECODE_FAILED"
    RAW_FRAME_WRITE_FAILED = "RAW_FRAME_WRITE_FAILED"
    PROCESSED_FRAME_WRITE_FAILED = "PROCESSED_FRAME_WRITE_FAILED"
    FACE_NOT_FOUND = "FACE_NOT_FOUND"
    MULTIPLE_FACE_CANDIDATES = "MULTIPLE_FACE_CANDIDATES"
    PRIMARY_FACE_LOW_SCORE = "PRIMARY_FACE_LOW_SCORE"
    LEFT_EYE_NOT_FOUND = "LEFT_EYE_NOT_FOUND"
    RIGHT_EYE_NOT_FOUND = "RIGHT_EYE_NOT_FOUND"
    LEFT_IRIS_NOT_FOUND = "LEFT_IRIS_NOT_FOUND"
    RIGHT_IRIS_NOT_FOUND = "RIGHT_IRIS_NOT_FOUND"
    HEAD_POSE_INVALID = "HEAD_POSE_INVALID"
    GAZE_MODEL_FAILED = "GAZE_MODEL_FAILED"
    GAZE_ESTIMATORS_DISAGREE = "GAZE_ESTIMATORS_DISAGREE"
    SCHEMA_VALIDATION_FAILED = "SCHEMA_VALIDATION_FAILED"


class CliErrorCode(StrEnum):
    USAGE = "USAGE"
    INPUT_NOT_FOUND = "INPUT_NOT_FOUND"
    UNSUPPORTED_VIDEO = "UNSUPPORTED_VIDEO"
    PIPELINE_NOT_IMPLEMENTED = "PIPELINE_NOT_IMPLEMENTED"
    SCHEMA_VALIDATION_FAILED = "SCHEMA_VALIDATION_FAILED"
    MODEL_ASSET_MISSING = "MODEL_ASSET_MISSING"
    MODEL_ASSET_CHECKSUM_MISMATCH = "MODEL_ASSET_CHECKSUM_MISMATCH"
    MODEL_LICENSE_NOT_APPROVED = "MODEL_LICENSE_NOT_APPROVED"


class FrameStatus(StrEnum):
    OK = "OK"
    ERROR = "ERROR"
